source "https://rubygems.org"
source "https://rubygems.cinc.sh" do
  gem "omnibus"
  gem "omnibus-software"
end
gem "artifactory"

gem "ffi", ">= 1.9.14", "!= 1.13.0"

gem "ffi-yajl", "2.6.0"

# This development group is installed by default when you run `bundle install`,
# but if you are using Omnibus in a CI-based infrastructure, you do not need
# the Test Kitchen-based build lab. You can skip these unnecessary dependencies
# by running `bundle config set --local without development` to speed up build times.
group :development do
  # Use Berkshelf for resolving cookbook dependencies
  gem "berkshelf", ">= 7.0"

  # Use Test Kitchen with Vagrant for converging the build environment
  gem "kitchen-vagrant", ">= 1.3.1"
  gem "test-kitchen", ">= 1.23"
  gem "winrm-fs", "~> 1.0"
end
