source "https://rubygems.org"
main_gemspec = File.expand_path("cinc-auditor-bin.gemspec", __dir__)
if File.exist?(main_gemspec)
  gemspec name: "cinc-auditor-bin"
else
  gemspec name: "cinc-auditor-core-bin"
end
